### ISSUE TITLE
GlazedLists Website is Down

### ISSUE THREAD

**Issue by bpangburn** [glazedlists/glazedlists#710] opened 2023-08-21 21:37 UTC
Entering, http://www.glazedlists.com (or just http://glazedlists.com) redirects the browser to https://sites.google.com/site/sites/system/errors/ProxiedWebspaceNotFound?host=www.glazedlists.com&webspace=glazedlists

This page is titled "Configuration error" and has the following content:
`www.glazedlists.com points to the site "glazedlists" which does not exist. Please contact the domain administrator.`

As I recall the site was never configured with a TLS certificate so did not support https://

There was some nice content on the old website (tutorials, etc) so it would be great to have that content restored somewhere. One option may be to use the GitHub "Pages" feature to host the content and then setup a redirect at the domain registrar level to point/redirect to the GitHub page(s).

Seems this would have the added benefit of automatically supporting https/TLS without manual intervention.

**Comment by hbrands** [comment] 2023-08-26 09:19
Thanks for the info.
I think this was/is caused by the automatic migration from the old to new Google Sites functionality.
Unfortunately, the connection to the custom domain was lost.
For the time being, the website content should be accessible again at

https://sites.google.com/view/glazedlists/

@robeden You should also have access to the Glazed Lists Google Sites and you are owner of the custom domain.
Maybe you are able to restore the connection to www.glazedlists.com ?
I found this help site:
https://support.google.com/sites/answer/9068867?sjid=7745742441900503380-EU

**Comment by robeden** [comment] 2023-08-27 02:20
Man, Google has made this process weird. I think it all should be fixed but as of this moment it's still resulting in an error due to SSL errors. I'm hoping this will be fixed shortly with new certs on their end. I'll monitor tomorrow to see how it goes.

**Comment by robeden** [comment] 2023-08-27 02:31
I checked again before bed and it looks like it's good-to-go now. Let me know if you continue to have issues.

**Closed by robeden** 2023-08-27 02:31 UTC

**Comment by bpangburn** [comment] 2023-08-27 03:06
Site generally looks good and glad to see it back up and running with TLS. Thanks!

Note the "Releases" child pages are rendering a little weird. Seems like an artifact of the old format. (i)Frame issue?

**Comment by hbrands** [comment] 2023-08-27 18:29
Thanks Rob! Seems to work fine now. 

And yes, some pages look not optimal, probably due to the migration process.
I'll have a look shortly.
