### ISSUE TITLE
IndexOutOfBoundsExceptions and NullPointerExceptions with JXTable on a filtered list

### ISSUE THREAD

**Issue by mauromol** [glazedlists/glazedlists#628] opened 2017-06-02 12:52 UTC
I wrote this on the users mailing list some days ago, but I think it is dead with java.net altogether.

I'm using GlzedLists 1.10.0 on Java 8 with SwingX 1.6.5-1. I have severe problems with table row selection.

This is what I have:

- a source BasicEventList
- this is filtered with a FilterList (controlled by a proper SearchEngineTextFieldMatcherEditor bound to a JXSearchField for text search)
- this is then sorted with a SortedList and a proper comparator

I'm installing this on a `JXTable` with `JXTableSupport.install(JXTable, EventList, TableFormat, SortedList, Object)`. Then, on the `JXTable` I set `setRowSelectionAllowed(true)` and `setSelectionMode(ListSelectionModel.SINGLE_SELECTION)`.

All works fine with regards to filtering and sorting. Selection, instead, works fine until I start to filter the list: after I do this, exceptions occurs in an apparently random fashion by just clicking on rows in the `JXTable`. It's so easily reproducible in my case that I was wondering whether I'm doing something wrong: I simply need to click on some rows, filter the table, click on some other rows, remove the filter, click on some other rows, etc. At some point of this action sequence, exception occurs.

A couple of examples:

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 20, Size: 12
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at ca.odell.glazedlists.impl.gui.ThreadProxyEventList.get(ThreadProxyEventList.java:139)
    at ca.odell.glazedlists.ListSelection.setAllColor(ListSelection.java:545)
    at ca.odell.glazedlists.ListSelection.deselectAll(ListSelection.java:525)
    at ca.odell.glazedlists.swing.DefaultEventSelectionModel.clearSelection(DefaultEventSelectionModel.java:383)
    at javax.swing.JTable.clearSelection(JTable.java:2117)
    at javax.swing.JTable.clearSelectionAndLeadAnchor(JTable.java:2125)
    at javax.swing.JTable.tableChanged(JTable.java:4445)
    at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1561)
    at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
    at ca.odell.glazedlists.impl.swing.DefaultTableModelEventAdapter.fireTableDataChanged(DefaultTableModelEventAdapter.java:89)
    at ca.odell.glazedlists.impl.swing.ManyToOneTableModelEventAdapter.fireOneTableModelEvent(ManyToOneTableModelEventAdapter.java:70)
    at ca.odell.glazedlists.impl.swing.ManyToOneTableModelEventAdapter.listChanged(ManyToOneTableModelEventAdapter.java:54)
    at ca.odell.glazedlists.swing.DefaultEventTableModel.handleListChange(DefaultEventTableModel.java:131)
    at ca.odell.glazedlists.swing.DefaultEventTableModel.listChanged(DefaultEventTableModel.java:120)
    at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:434)
    at ca.odell.glazedlists.event.ListEventAssembler$ListEventFormat.fire(ListEventAssembler.java:430)
    at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:469)
    at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:365)
    at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:326)
    at ca.odell.glazedlists.FilterList.constrained(FilterList.java:399)
    at ca.odell.glazedlists.FilterList.changeMatcher(FilterList.java:295)
    at ca.odell.glazedlists.FilterList.changeMatcherWithLocks(FilterList.java:276)
    at ca.odell.glazedlists.FilterList.access$100(FilterList.java:51)
    at ca.odell.glazedlists.FilterList$PrivateMatcherEditorListener.changedMatcher(FilterList.java:454)
    at ca.odell.glazedlists.matchers.AbstractMatcherEditorListenerSupport.fireChangedMatcher(AbstractMatcherEditorListenerSupport.java:46)
    at ca.odell.glazedlists.matchers.AbstractMatcherEditor.fireConstrained(AbstractMatcherEditor.java:60)
    at ca.odell.glazedlists.matchers.TextMatcherEditor.setTextMatcher(TextMatcherEditor.java:347)
    at ca.odell.glazedlists.matchers.SearchEngineTextMatcherEditor.refilter(SearchEngineTextMatcherEditor.java:88)
    at ca.odell.glazedlists.swing.SearchEngineTextFieldMatcherEditor$FilterHandler.actionPerformed(SearchEngineTextFieldMatcherEditor.java:74)
    at javax.swing.JTextField.fireActionPerformed(JTextField.java:508)
    at javax.swing.JTextField.postActionEvent(JTextField.java:721)
    at org.jdesktop.swingx.JXSearchField.postActionEvent(JXSearchField.java:793)
    at org.jdesktop.swingx.JXSearchField$7.actionPerformed(JXSearchField.java:687)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Another one:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at ca.odell.glazedlists.impl.adt.BarcodeNode.insertWhite(BarcodeNode.java:153)
    at ca.odell.glazedlists.impl.adt.Barcode.addWhite(Barcode.java:137)
    at ca.odell.glazedlists.impl.adt.BarcodeNode.unlink(BarcodeNode.java:762)
    at ca.odell.glazedlists.impl.adt.BarcodeNode.unlink(BarcodeNode.java:734)
    at ca.odell.glazedlists.impl.adt.BarcodeNode.setBaseCase(BarcodeNode.java:584)
    at ca.odell.glazedlists.impl.adt.BarcodeNode.set(BarcodeNode.java:437)
    at ca.odell.glazedlists.impl.adt.Barcode.set(Barcode.java:203)
    at ca.odell.glazedlists.ListSelection.setSubRangeOfRange(ListSelection.java:1053)
    at ca.odell.glazedlists.ListSelection.setSelection(ListSelection.java:731)
    at ca.odell.glazedlists.swing.DefaultEventSelectionModel.setSelectionInterval(DefaultEventSelectionModel.java:258)
    at javax.swing.JTable.changeSelectionModel(JTable.java:2389)
    at javax.swing.JTable.changeSelection(JTable.java:2458)
    at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1115)
    at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038)
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
    at java.awt.Component.processMouseEvent(Component.java:6530)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

By debugging, it seems like to me that what happens until `JTable.changeSelectionModel(JTable.java:2389)` is fine: `ListSelectionModel.setSelectionInterval(int, int)` is invoked with the proper selected row index. In fact, if I replace the selection model with a `DefaultListSelectionModel `after I install GlazedLists on the `JXTable`, all seems to work perfectly fine.

So, I have some questions on this:

- am I doing something foundamentally wrong?
- when I use `JXTableSupport.install()`, why must I specify both the source event list and the sorted list, with all the risks that this may imply if they are not related to each other or built wrongly? Isn't the SortedList the only information this method should require? I would have expected it to take the SortedList source list as the data source for the table model... Javadoc instead says: "It's possible to layer further transforms *above* the `SortedList` and pass one of those in as the data source"... so this seems to suggest that, in my case, I may build my list chain in this alternative way:
    BasicEventList => SortedLIst => FilterList
    and then still pass the `FilterList` as the data source and the `SortedList` as the sorted list used by the `TableComparatorChooser`; but in my case I would say this is less efficient, because sorting would be performed on the whole (possibly long) source list instead of the filtered one. Anyway, I can't think of any proper use cases where this flexibility of `JXTableSupport.install()` requesting two different input lists can be beneficial
- it's not clear to me what is the benefit of having `JXTableSupport.install()` to build and install a `DefaultEventSelectionModel` on the `JXTable`; Swing's `DefaultListSelectionModel` seems to work just fine... After all, the selection model is not directly tied to the table model and whenever a row insert/delete notification is received from the table model, `JTable.tableRowsInserted(TableModelEvent)` and `tableRowsDeleted(TableModelEvent)` take care of notifying the selection model about the inserted/removed rows (in case selection must be adjusted).... Probably it's useful if the user wants to intercept selection changes and forward them immediately on other event lists, but couldn't this be an opt-in feature (easily obtainable by just changing the `JXTable` selection model at a later time, since JXTableSupport doesn't do anything special for this)?

Thanks in advance for any help.

**Comment by hbrands** [comment] 2017-06-03 20:26
First, to troubleshoot your problem:
Does it make any difference when you call
`JXTable #setFillsViewportHeight(false)`
on your JXTable before installing JXTableSupport?

**Comment by mauromol** [comment] 2017-06-05 07:53
Hi Holger! Just tried some frantic clicking with and without `fillsViewportHeight`. Indeed, it seems like that with this property enabled the problem happens, while it does not if this property is disabled.
Unfortunately, though, I can't think of any serious use of a table in a scroll pane with `fillsViewportHeight` set to `false`, unless I tweak the scroll pane background colour to match the table one...

**Comment by hbrands** [comment] 2017-06-05 17:52
Ok, at least I know WHAT causes the problem. But I have to investigate more WHY it fails this way.
I think it's caused by or related to the fix for issue #578

**Comment by hbrands** [comment] 2017-06-11 18:37
I checked in a workaround for this problem. It was an ordering issue where the table model received list events before the selection model/ListSelection, which in this case is a problem, because the table#tableChanged method triggers a change in the ListSelection which at this point isn't yet up to date.
Now ListSelection and selection model is updated before the table model, which prevents this issue. But we have to see if it causes other regressions. 
Could you try out the latest 1.11 snapshot version deployed to Maven repo:
https://oss.sonatype.org/content/repositories/snapshots/

Manual download here:
https://oss.sonatype.org/content/repositories/snapshots/com/glazedlists/glazedlists/1.11-SNAPSHOT/

**Comment by hbrands** [comment] 2017-06-20 20:10
@mauromol Do you have time to test the 1.11 snapshot?

**Comment by mauromol** [comment] 2017-06-20 21:22
Sorry for the delay, I will try to do some testing during these days. Thank you!

**Comment by mauromol** [comment] 2017-06-22 12:44
@hbrands I did some rapid tests, comparing the GL 1.10 and 1.11-SNAPSHOT behaviour, and with 1.11-SNAPSHOT I don't get the exceptions I get with 1.10. So, I think the problem is fixed now, even though I didn't perform exhaustive tests. I also checked that the selected elements are coherent with the UI state.
Thank you!!

By the way, this continuous groupid:artifactid change is a pain... ;-)

**Comment by robeden** [comment] 2017-06-22 14:31
> By the way, this continuous groupid:artifactid change is a pain... ;-)

Yes. We did it this one more time so we'd never have to do it again.

**Comment by hbrands** [comment] 2017-06-22 16:02
Ok, I consider this done. Thanks for verifying.

**Closed by hbrands** 2017-06-22 16:02 UTC
Labels: component: swingx
