### ISSUE TITLE
Release 1.11.0: error: package ca.odell.glazedlists.calculation does not exist

### ISSUE THREAD

**Issue by Kolbk17** [glazedlists/glazedlists#650] opened 2018-01-16 19:24 UTC
Building Glazedlists-1.11.0 from source using Gradle on a CentOS7 Linux VM, I get the above error pertaining to the following file. glazedlists-1.11.0/extensions/jfreechart/src/main/java/ca/odell/glazedlists/jfreechart/CalculationCategoryDataset.java Line:10:import ca.odell.glazedlists.calculation.Calculation; 

It seems this file was not included in the release (it is not in the github in the core/src/main/java/ca/odell/glazedlists/ directory like the other imports are), or was misplaced.

**Comment by hbrands** [comment] 2018-01-16 20:38
Just to clarify:
are you building from source by checking out the project from GitHub or have you downloaded the Glazed Lists distribution ZIP file and built from that source?
What command did you execute: _gradlew build_?
Could you provide the concrete stacktrace?
(On Windows I cannot reproduce the issue)
Thanks!

**Comment by hbrands** [comment] 2018-01-16 20:40
BTW, ca.odell.glazedlists.calculation.Calculation should be located in the calculation extension (directory extensions/calculation/...)

**Comment by Kolbk17** [comment] 2018-01-16 21:54
I obtained the source code from http://repo1.maven.org/maven2/com/glazedlists/glazedlists/1.11.0/ it appeared to be the same as that on the GitHub but I can't be certain. I am not building on Windows, this is a Linux build. The command I used was: '$ gradle assemble' which was the first task in the set of gradle tasks that can be executed on the project.
Thanks for pointing me to the file location, I will look into it further, and if I still encounter problems, I will provide a stack trace for you.

**Comment by Kolbk17** [comment] 2018-01-16 22:12
I have solved the issue. I see now that you already have the solution implemented in the GitHub.

Also, as a side note to my build complications, would it be all right to start a discussion here regarding jfxrt.jar, jfreechart.jar, and jcommon.jar?

**Comment by hbrands** [comment] 2018-01-17 19:18
Hmm, after releasing 1.11 we didn't change anything in the glazedlists-1.11.x branch.
On master we moved for the next release to build against Java 8.
So I don't understand what your problem was. Anyway we're glad you could resolve the issue.
For further discussions the best place is on the Gitter channel:
https://gitter.im/glazedlists/glazedlists
I'll close this issue.

**Closed by hbrands** 2018-01-17 19:18 UTC
